### ISSUE TITLE
[question] Automatic Theme Switching

### ISSUE THREAD

**Issue by calebpanza** [aleqsio/expo-quickstart-template#1]
Hey! Love this template and plan to use it for many projects to come.

I'm having trouble enabling the auto-switching of the theme based on the system theme. I've read through the Expo docs and followed the instructions but nothing seems to be working.

Any ideas?

Thanks!!

**Comment by aleqsio** [comment]
Sorry, I don't really know more than written here:
https://docs.expo.dev/develop/user-interface/color-themes/

You might need a physical device for it to work though!
